### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by StageGuard** [StageGuard/OsuMapSuggester#1]
## 功能
- [ ] 以图片方式显示推图结果，附带一个链接可以直接像官网一样一键导入谱面（前端做个重定向）
- [ ] 以图片方式显示所有自定义谱面类型规则
- [ ] 支持编辑自定义谱面类型规则
- [ ] 实现 Web 端添加，编辑自定义谱面类型规则（做一个session池防止越级编辑）
- [ ] 分析玩家 pp+ 根据强弱项推图
## 已知问题
- [ ] 请求 osu api 如果 timeout 了不会显示错误
- [ ] 在 QQ 聊天交互编辑的时候还会触发指令（把这个抽象出来，做个缓存池）
- [ ] pp + 算法还有点问题
